openapi: "3.0.1"
info:
  title: "resize-API"
  description: "Created by AWS Lambda"
  version: "2025-07-17 00:12:54UTC"
servers:
- url: "https://ltgchi86r4.execute-api.us-east-1.amazonaws.com/{basePath}"
  variables:
    basePath:
      default: "default"
paths:
  /resize:
    x-amazon-apigateway-any-method:
      responses:
        default:
          description: "Default response for ANY /resize"
      x-amazon-apigateway-integration:
        payloadFormatVersion: "2.0"
        type: "aws_proxy"
        httpMethod: "POST"
        uri: "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:312702121860:function:resize/invocations"
        connectionType: "INTERNET"
x-amazon-apigateway-cors:
  maxAge: -42
  allowCredentials: false
  allowOrigins:
  - "*"
x-amazon-apigateway-importexport-version: "1.0"
